services:
  h2:
    image: zeilush/h2
    container_name: h2
    ports:
      - "1521:1521"
    networks:
      - spbstu

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/mem:task_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      SPRING_PROFILES_ACTIVE: db
      SPRING_DATASOURCE_USERNAME: h2
      SPRING_DATASOURCE_PASSWORD: h2
    depends_on:
      - h2
    networks:
      - spbstu

networks:
  spbstu:
